- name: Create cifs_server
  na_ontap_cifs_server:
    state: present
    vserver: "{{ svm_name }} "
    domain: "{{ cifs_domain }}" 
    workgroup: {{cifs_workgroup }}"
    admin_user_name: "{{ cifs_username }}"
    admin_ password:  "{{ cifs_password }}"    
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"