- name: change nfs status
  na_ontap_nfs:
    state: present
    service_state: started
    vserver: "{{ item.svm_name }}" 
    nfsv3: enabled
    nfsv4: disabled
    nfsv41: disabled
    vstorage_state: enabled
    # nfsv4_id_domain: example.com #
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  with_items: "{{ SVMs }}"

- name: Create iscsi service
  na_ontap_iscsi:
    state: present
    service_state: started
    vserver: "{{ item.svm_name }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  with_items: "{{ SVMs }}"